title: ð“† carocim
author: Carocim
email: jjmessiah22@gmail.com
url: https://carocim.github.io
baseurl: "/"
description: > 
  <p>
  <span style="color: #FFFFFF; font-size: 1.2em;">ã‚«ãƒ­ã‚·ãƒ </span>
  <br><br>
  a digital garden for my thoughts, experiments, and curiosities 
  <br><br>
  <span style="font-weight: bold;">links:</span><br>
  â€¢ <a href="https://hardcover.app/@carocim" style="color: #FFFFFF;">my current book tracker</a> or check <a href="https://www.goodreads.com/paradocim" style="color: #FFFFFF;">goodreads</a><br>
  â€¢ <a href="https://discord.com/users/689466178883944528" style="color: #FFFFFF;">main contact</a><br> if you want to reach out
  â€¢ <a href="https://open.spotify.com/user/314qg3qowcbtctv4sf5pcsrqdytm?si=32fe8363b0d74c87" style="color: #FFFFFF;">playlists</a> over the years<br>
  â€¢ <a href="https://github.com/Carocim" style="color: #FFFFFF;">projects</a><br>
  </p>
permalink: /:slug.html
favicon: "favicon.png"
remote_theme: riggraz/no-style-please
theme_config:
  appearance: "auto"
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  show_description: true
sass:
  style: :compressed
plugins:
  - jekyll-feed
  - jekyll-seo-tag
collections:
  reco:
    output: true
    future: true